
export interface TimezoneOption {
  value: string;
  label: string;
}

export const timezoneOptions: TimezoneOption[] = [
  { value: "UTC", label: "UTC (Coordinated Universal Time)" },
  { value: "America/New_York", label: "United States (New York - UTC -5:00)" },
  { value: "America/Chicago", label: "United States (Chicago - UTC -6:00)" },
  { value: "America/Denver", label: "United States (Denver - UTC -7:00)" },
  { value: "America/Los_Angeles", label: "United States (Los Angeles - UTC -8:00)" },
  { value: "America/Anchorage", label: "United States (Anchorage - UTC -9:00)" },
  { value: "America/Honolulu", label: "United States (Honolulu - UTC -10:00)" },
  { value: "America/Phoenix", label: "United States (Phoenix - UTC -7:00)" },
  { value: "America/Puerto_Rico", label: "Puerto Rico (San Juan - UTC -4:00)" },
  { value: "Europe/London", label: "United Kingdom (London - UTC +0:00)" },
  { value: "Europe/Paris", label: "France (Paris - UTC +1:00)" },
  { value: "Europe/Berlin", label: "Germany (Berlin - UTC +1:00)" },
  { value: "Europe/Madrid", label: "Spain (Madrid - UTC +1:00)" },
  { value: "Europe/Rome", label: "Italy (Rome - UTC +1:00)" },
  { value: "Europe/Zurich", label: "Switzerland (Zurich - UTC +1:00)" },
  { value: "Europe/Amsterdam", label: "Netherlands (Amsterdam - UTC +1:00)" },
  { value: "Europe/Stockholm", label: "Sweden (Stockholm - UTC +1:00)" },
  { value: "Europe/Brussels", label: "Belgium (Brussels - UTC +1:00)" },
  { value: "Europe/Vienna", label: "Austria (Vienna - UTC +1:00)" },
  { value: "Europe/Athens", label: "Greece (Athens - UTC +2:00)" },
  { value: "Europe/Istanbul", label: "Turkey (Istanbul - UTC +3:00)" },
  { value: "Europe/Moscow", label: "Russia (Moscow - UTC +3:00)" },
  { value: "Asia/Dubai", label: "United Arab Emirates (Dubai - UTC +4:00)" },
  { value: "Asia/Kolkata", label: "India (New Delhi/Kolkata - UTC +5:30)" },
  { value: "Asia/Shanghai", label: "China (Beijing/Shanghai - UTC +8:00)" },
  { value: "Asia/Tokyo", label: "Japan (Tokyo - UTC +9:00)" },
  { value: "Asia/Singapore", label: "Singapore (Singapore - UTC +8:00)" },
  { value: "Asia/Seoul", label: "South Korea (Seoul - UTC +9:00)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (Hong Kong - UTC +8:00)" },
  { value: "Asia/Bangkok", label: "Thailand (Bangkok - UTC +7:00)" },
  { value: "Asia/Ho_Chi_Minh", label: "Vietnam (Ho Chi Minh City - UTC +7:00)" },
  { value: "Asia/Kuala_Lumpur", label: "Malaysia (Kuala Lumpur - UTC +8:00)" },
  { value: "Asia/Jakarta", label: "Indonesia (Jakarta - UTC +7:00)" },
  { value: "Asia/Manila", label: "Philippines (Manila - UTC +8:00)" },
  { value: "Australia/Sydney", label: "Australia (Sydney - UTC +10:00)" },
  { value: "Australia/Melbourne", label: "Australia (Melbourne - UTC +10:00)" },
  { value: "Australia/Brisbane", label: "Australia (Brisbane - UTC +10:00)" },
  { value: "Australia/Perth", label: "Australia (Perth - UTC +8:00)" },
  { value: "Pacific/Auckland", label: "New Zealand (Auckland - UTC +12:00)" },
  { value: "Pacific/Fiji", label: "Fiji (Suva - UTC +12:00)" },
  { value: "Pacific/Honolulu", label: "Hawaii (Honolulu - UTC -10:00)" },
  { value: "Africa/Johannesburg", label: "South Africa (Johannesburg - UTC +2:00)" },
  { value: "Africa/Cairo", label: "Egypt (Cairo - UTC +2:00)" },
  { value: "Africa/Lagos", label: "Nigeria (Lagos - UTC +1:00)" },
  { value: "Africa/Nairobi", label: "Kenya (Nairobi - UTC +3:00)" },
  { value: "Africa/Casablanca", label: "Morocco (Casablanca - UTC +0:00)" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina (Buenos Aires - UTC -3:00)" },
  { value: "America/Sao_Paulo", label: "Brazil (São Paulo - UTC -3:00)" },
  { value: "America/Mexico_City", label: "Mexico (Mexico City - UTC -6:00)" },
  { value: "America/Toronto", label: "Canada (Toronto - UTC -5:00)" },
  { value: "America/Vancouver", label: "Canada (Vancouver - UTC -8:00)" },
];
