// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjzzdynuzrpklgexabzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qenpkeW51enJwa2xnZXhhYnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTc5NzgsImV4cCI6MjA2MDI5Mzk3OH0.3HDjeXJKvyC_bBIzI_ca6kmEOtFULBXkL0jAX53MH6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);